### ISSUE TITLE
Bug Recuperação Atendimento

### ISSUE THREAD

**Issue by m-ribeiro** [andrewebdeveloper/brtalk#1]
Quando estou em um atendimento e por uma acaso fecho a janelinha do cliente, quando clico novamente ele não traz o dialogo anterior. A janela vem vazia...

**Comment by alansystem** [comment]
Mas isso não seria um processo natural de qualquer chat? Afinal a conversa foi finalizada!

**Comment by pixies** [comment]
Os chats mais comuns hj não apagam, não.
E realmente seria interessante manter o registro (log) da conversa.
Como o Facebook, WhatsApp, telegram, faz , e usam um timestamp para controlar.

**Comment by andrelimeira** [comment]
Eu não cheguei a olhar essa issue, mas acho que ele comentou sobre estar em um atendimento e fechar a janela, dps clicar para abrir novamente e não mostrar o histórico. (No caso o atendimento ainda não foi finalizado).

Agora se for com relação a histórico, isso já existe. Tem um menu Histórico onde você coloca a data e ele lista todos os atendimentos.

**Comment by m-ribeiro** [comment]
Isso mesmo André! 

No caso eu me referi a um atendimento que ainda não tinha finalizado. Ou seja, foi clicado no "X" para fechar a janela e depois clicado no atendimento novamente para dar continuidade.

Abraço

**Comment by andrelimeira** [comment]
Corrigido galera, agora quando você fecha um atendimento em andamento eu criei uma função no .js para fazer um ajax no próprio arquivo do history_message onde retorna o histórico de mensagem e exibo ele na tela do usuário. Obrigado =) 

E que venha mais issues <3

**Comment by m-ribeiro** [comment]
Olá fiz um teste e me parece que não foi corridigo. Segue os prints das telas. 

Abraço
![3-cliquei novamente](https://cloud.githubusercontent.com/assets/6692736/16006351/042f368a-3143-11e6-9588-ed3fa04f8f48.png)
![2-fechei janela](https://cloud.githubusercontent.com/assets/6692736/16006350/042a83a6-3143-11e6-82c0-48844d790dce.png)
![1-teste de envio](https://cloud.githubusercontent.com/assets/6692736/16006349/042962a0-3143-11e6-803f-9a0aeae88fef.png)

**Comment by andrelimeira** [comment]
@m-ribeiro eu não atualizei os código no ftp deste domínio para testes... apenas o repositório do github. Vou fazer a atualização no ftp de demonstração.

Obrigado
