### ISSUE TITLE
Remover dependência do MySQL

### ISSUE THREAD

**Issue by jeanjar** [andrewebdeveloper/brtalk#3]
implementar os métodos de conexão e consultas no banco de modo que funcione com os bancos de dados mais utilizados.
1 - PostgreSQL
2 - MySQL
3 - Sqlite
...

**Comment by andrelimeira** [comment]
Amigo, você chegou a testar o brTalk no PostgreSQL ? Acredito que ele já seja compatível, pois o PDO faz o gerenciamento do driver para o SGBD escolhido (mysql, postgresql, etc)
