### ISSUE TITLE
Melhorar ambiente de demonstração

### ISSUE THREAD

**Issue by wpbarcelos** [andrewebdeveloper/brtalk#4]
Erro 500 após o cliente informar nome e email e entrar na pagina http://lab.andrewd.com.br/brtalk/cliente/index.php

Melhorar README.md para informar a pagina do cliente

**Comment by andrelimeira** [comment]
Boa noite, já estou resolvendo os problemas com o servidor e o ambiente de teste. 

A página do cliente não precisa ser especificada no readme, já que os diretórios no próprio código fonte estão comocliente/ e atendente/, mas o programador que vai definir esses diretórios bem como o link de atalho para o acesso do cliente durante a instalação e configuração do brTalk no site/sistema.

Agradeço a sugestão

**Comment by andrelimeira** [comment]
Finalizei algumas correções e melhorias no ambiente de teste. 
Também notei que alguns bloqueadores de anúncios (ABP, ADBlock, etc) estão bloqueando o arquivo sound.swf devido tamanho e não está exibindo os novos clientes no painel administrador, em breve envio um patch de correção.

Feliz ano novo =)

**Comment by andrelimeira** [comment]
Pode ser sim, mas a ideia agora seria no minimo usar WebSocket e remover essa responsabilidade do javascript e também talvez(opcional) construir toda essa comunicação com uma API usando um micro-framework tipo o Slim, então sim o sistema web iria consumir desta API e para quem sabe uma versão mobile também se comunicando com essa API. 

Melhor fechar esta issue e abrir uma nova p/ melhorias e novas sugestões da nova versão, também preciso de ajuda dependendo o tamanho do projeto.

**Comment by wpbarcelos** [comment]
Pensei tambem em uma feature mais para frente... um plugin para adicionar aos sites estatico de atendimento online.
